version: '3'
services:
  test:
    build:
      context: .
    links:
      - selenium
    environment:
      SELENIUM_URL: 'http://selenium:4444/wd/hub'
      DRIVER: chrome
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
      AWS_REGION: 'us-east-1'
      AWS_ENDPOINT: 'http://s3.${SERVER_DOMAIN:-et.127.0.0.1.nip.io}:${SERVER_PORT:-3100}'
      AWS_S3_FORCE_PATH_STYLE: 'true'
      BUNDLE_WITH: development,test
      ENVIRONMENT:
      SCREENSHOT_S3_ACCESS_KEY_ID:
      SCREENSHOT_S3_BUCKET:
      SCREENSHOT_S3_KEY_PREFIX:
      SCREENSHOT_S3_REGION:
      SCREENSHOT_S3_SECRET_ACCESS_KEY:
    volumes:
      - ../../:/app
      - test_gem_cache:/usr/local/bundle
    networks:
      - test_framework
  selenium:
    image: "selenium/standalone-chrome-debug"
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "${SELENIUM_PORT:-4444}:4444"
      - "${SELENIUM_VNC_PORT:-5900}:5900"
    networks:
      - test_framework
volumes:
  test_gem_cache:
networks:
  test_framework:
    external:
      name: test_server_et_full_system
